### ISSUE TITLE
question

### ISSUE THREAD

**Issue by astrocycles** [Blah2014/PageSpeed-Insights#2]
Hi,

When I'm adding multiple html file like index.hmlt /about.html . only index file is compiled in the dist folder. What is the solution ? 
Also is it possible to adapt the gulp file with an angular 2 project ?

many thanks

**Comment by Blah2014** [comment]
This project intended to be used with single web page application as an example Angular 1/2.  
You can use it with index.html, about.html and etc.   
What you need is to extend logic in ```gulpfile.js```  or create ```gulpfile-about.js``` which is a copy of ```gulpfile.js``` with new logic for ```about.html``` and run ```gulp --gulpfile gulpfile-about.js```
